WITH BIG_FISH AS (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO AS FI
    GROUP BY FISH_TYPE
)
SELECT
    FISH_INFO.ID,
    FISH_NAME_INFO.FISH_NAME,
    BIG_FISH.LENGTH
FROM BIG_FISH
    JOIN FISH_NAME_INFO ON BIG_FISH.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    JOIN FISH_INFO ON BIG_FISH.FISH_TYPE = FISH_INFO.FISH_TYPE AND BIG_FISH.LENGTH = FISH_INFO.LENGTH