WITH RECURSIVE GEN_DATA AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT
        ECOLI_DATA.ID,
        ECOLI_DATA.PARENT_ID,
        (GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA
        JOIN GEN_DATA ON ECOLI_DATA.PARENT_ID = GEN_DATA.ID
),
PARENT_IDS AS (
    SELECT
        DISTINCT(PARENT_ID)
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
SELECT
    COUNT(*) AS COUNT,
    GENERATION
FROM GEN_DATA
WHERE ID NOT IN (SELECT PARENT_ID FROM PARENT_IDS)
GROUP BY GENERATION