WITH FRONT_CODE AS (
    SELECT
        SUM(CODE) AS SKILL_CODE
    FROM SKILLCODES
        WHERE CATEGORY = 'Front End'
)
SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS, FRONT_CODE
WHERE DEVELOPERS.SKILL_CODE & FRONT_CODE.SKILL_CODE
ORDER BY ID ASC