SELECT
    HR_EMPLOYEES.EMP_NO,
    HR_EMPLOYEES.EMP_NAME,
    CASE 
        WHEN AVG(HR_GRADE.SCORE) < 80 THEN 'C'
        WHEN AVG(HR_GRADE.SCORE) < 90 THEN 'B'
        WHEN AVG(HR_GRADE.SCORE) < 96 THEN 'A'
        ELSE 'S'
    END AS GRADE,
    CASE 
        WHEN AVG(HR_GRADE.SCORE) < 80 THEN SAL * 0
        WHEN AVG(HR_GRADE.SCORE) < 90 THEN SAL * 0.1
        WHEN AVG(HR_GRADE.SCORE) < 96 THEN SAL * 0.15
        ELSE SAL * 0.2
    END AS BONUS
FROM HR_EMPLOYEES 
    LEFT JOIN HR_GRADE ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
GROUP BY EMP_NO, EMP_NAME