
WITH RECURSIVE SET_HOUR AS (
    SELECT
        0 AS HOUR,
        0 AS COUNT
    UNION ALL
    SELECT
        HOUR + 1,
        0 AS COUNT
    FROM SET_HOUR
    WHERE HOUR < 23
),
SET_COUNT AS (
    SELECT 
        HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR ASC
)
SELECT 
    SET_HOUR.HOUR,
    IFNULL(SET_COUNT.COUNT, 0) AS COUNT
FROM SET_HOUR
    LEFT JOIN SET_COUNT ON SET_HOUR.HOUR = SET_COUNT.HOUR